Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> print("hola, bienvenido a tu primer script")
... 
... a=input("digite un nombre")
... 
... b=int(input("digite un número"))
... 
... print("su nombre es ", a)
... 
... print("su número es ", b)
... 
... c=b**2
... 
